app/main/logger/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Objective to different logs</description>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{0000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

app/main/logger/objects/Log__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <label>Details</label>
    <type>TextArea</type>
</CustomField>

app/main/logger/objects/Log__c/fields/ErrorType__c.field-meta.xml
<CustomField>
    <fullName>ErrorType__c</fullName>
    <label>ErrorType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

app/main/logger/classes/Log.cls
public with sharing class Log {
    public static final String TYPE_ERROR = 'Error';

    private String type;
    private String errorType;
    private String message;
    private String stackTrace;
    private String scope;
    
    private Log(Exception e) {
        this.type = TYPE_ERROR;
        this.errorType = e.getTypeName();
        this.message = e.getMessage();
        this.stackTrace = e.getStackTraceString();
    }

    public static Log createLog(Exception ex, String scope) {
        Log l = new Log(ex);
        l.scope = scope;
        return l;
    }

    public String getType() {
        return this.type;
    }

    public String getErrorType() {
        return this.errorType;
    }

    public String getMessage() {
        return this.message;
    }

    public String getDetails() {
        return this.stackTrace;
    }

    public String getScope() {
        return this.scope;
    }

    public Log__c unwrap() {
        return new Log__c(
            Type__c = this.getType(),
            ErrorType__c = this.getErrorType(),
            Message__c = this.getMessage(),
            Details__c = this.getDetails(),
            Scope__c = this.getScope()
        );
    }
}